CREATE TABLE IF NOT EXISTS research_cache (
id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
cache_key VARCHAR(255) NOT NULL UNIQUE,
cache_value LONGTEXT NOT NULL,
created_at DATETIME NOT NULL
) ENGINE=InnoDB;