import os
from dotenv import load_dotenv

SUPPORTED_NETWORKS = os.getenv("SUPPORTED_NETWORKS").split(",")

ANCHAIN_API_BASE_URL = os.getenv("ANCHAIN_API_BASE_URL", "")
ANCHAIN_API_KEY = os.getenv("ANCHAIN_API_KEY", "")

CHAINALYSIS_API_BASE_URL = os.getenv("CHAINALYSIS_API_BASE_URL", "")
CHAINALYSIS_API_KEY = os.getenv("CHAINALYSIS_API_KEY", "")

SCORECHAIN_API_BASE_URL = os.getenv("SCORECHAIN_API_BASE_URL", "")
SCORECHAIN_API_KEY = os.getenv("SCORECHAIN_API_KEY", "")

MODEL_API_URL = os.getenv("MODEL_API_URL")
MODEL_NAME = os.getenv("MODEL_NAME")
MODEL_API_KEY = os.getenv("MODEL_API_KEY")

EXTRACTOR_MODEL_API_URL = os.getenv("EXTRACTOR_MODEL_API_URL")
EXTRACTOR_MODEL_NAME = os.getenv("EXTRACTOR_MODEL_NAME")
EXTRACTOR_MODEL_API_KEY = os.getenv("EXTRACTOR_MODEL_API_KEY")

MYSQL_DATABASE = os.getenv("MYSQL_DATABASE")
MYSQL_USER = os.getenv("MYSQL_USER")
MYSQL_PASSWORD = os.getenv("MYSQL_PASSWORD")
MYSQL_HOST=os.getenv("MYSQL_HOST")
MYSQL_PORT=os.getenv("MYSQL_PORT")